export const denimData = [
    {
      id: 1,
      name: "Acid Wash Zip Down Jacket",
      category: "Jackets",
      price: 7090.99,
      description:
        "Trendy acid wash zip down jacket for men, featuring a stylish design and comfortable fit. Perfect for adding a touch of edge to your wardrobe.",
      gender: "Male",
      image: "/acidWash.jpg",
      image2: "/acidWash2.jpg",
      image3: "/acidWash3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
  
    {
      id: 2,
      name: "High Rise Distressed Denim Shorts",
      category: "Shorts",
      price: 5040.99,
      description:
        "High rise distressed denim shorts, adding a touch of edge to your summer wardrobe. These shorts feature a high rise waist and distressed detailing, perfect for creating trendy casual looks.",
      gender: "Female",
      image: "/highSShorts.webp",
      image2: "/highSShorts2.jpg",
      image3: "/highSShorts3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
    {
      id: 3,
      name: "Ripped Denim Shorts",
      category: "Shorts",
      price: 3090.99,
      description:
        "Embrace laid-back style with our Ripped Denim Shorts, perfect for sunny days and warm nights. Made from soft denim fabric, these shorts feature distressed detailing for a casual, lived-in look. ",
      gender: "Male",
      image: "/ripshorts2.webp",
      image2: "/ripshorrt.jpg",
      image3: "/ripShorts.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
    {
      id: 4,
      name: "Seamed Bandeau Corset Dress",
      category: "Dresses",
      price: 9090.99,
      description:
        "Seamed bandeau corset dress, offering a sleek and sophisticated silhouette. This corset dress features seamed detailing and a bandeau neckline, making it a stylish choice for special occasions.",
      gender: "Female",
      image: "/bandeauCorset.webp",
      image2: "/bandeauCorset2.jpg",
      image3: "/bandeauCorset3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
  
    {
      id: 5,
      name: "Tie Cuff Denim Joggers",
      category: "Pants",
      price: 6090.99,
      description:
        "Stylish tie cuff denim joggers for women, perfect for a casual yet trendy look. These joggers feature a comfortable fit and chic design, making them a versatile addition to your wardrobe.",
      gender: "Female",
      image: "/tieCuff.webp",
      image2: "",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
    {
      id: 6,
      name: "Baggy Fit Jean",
      category: "Pants",
      price: 7040.99,
      description:
        "Baggy fit jeans for a comfortable and casual look. These jeans feature a loose fit and relaxed style, making them perfect for everyday wear.",
      gender: "Male",
      image: "/baggyFit.webp",
      image2: "/baggyFit2.webp",
      image3: "/baggyFit3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
    {
      id: 7,
      name: "Oversized Distressed Denim Jacket",
      category: "Jackets",
      price: 8090.99,
      description:
        "Oversized distressed denim jacket, perfect for a rugged look. This jacket offers both style and functionality, making it a versatile addition to your outerwear collection.",
      gender: "Male",
      image: "/overDistressed.webp",
      image2: "/overDistressed2.webp",
      image3: "/overDistressed3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 20,
    },
    {
      id: 8,
      name: "Plus Basic Straight Leg Jean",
      category: "Pants",
      price: 7040.99,
      description:
        "Plus size basic straight leg jeans, designed to provide a flattering fit for curvy figures. These jeans feature a classic straight leg silhouette and versatile design, making them a wardrobe essential for any occasion.",
      gender: "Female",
      image: "/plusBasic.webp",
      image2: "/plusBasic2.jpg",
      image3: "/plusBasic3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 20,
    },
  
    {
      id: 9,
      name: "Plus Denim Zip Up Shift Dress",
      category: "Dresses",
      price: 8090.99,
      description:
        "Plus size denim zip up shift dress, offering a chic and comfortable silhouette. This shift dress features a zip up front and denim fabric, making it a stylish choice for any casual occasion.",
      gender: "Female",
      image: "/zipUpDress.webp",
      image2: "/zipUpDress2.jpg",
      image3: "/zipUpDress3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 20,
    },
    {
      id: 10,
      name: "Denim Tiered Smock Dress",
      category: "Dresses",
      price: 7090.99,
      description:
        "Denim tiered smock dress, combining bohemian charm with contemporary style. This smock dress features tiered detailing and denim fabric, making it a chic and versatile addition to your wardrobe.",
      gender: "Female",
      image: "/smockDress.webp",
      image2: "/smockDress2.jpg",
      image3: "/smockDress3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 20,
    },
  
    {
      id: 11,
      name: "High Waisted Roll Hem Shorts",
      category: "Shorts",
      price: 4090.99,
      description:
        "High waisted roll hem shorts, offering a classic and versatile look. These shorts feature a high waisted design and rolled hem detailing, perfect for creating effortless summer outfits.",
      gender: "Female",
      image: "/hemShorts.webp",
      image2: "/hemShorts2.jpg",
      image3: "/hemShorts3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 20,
    },
    {
      id: 12,
      name: "Revigour vintage Skate Jean",
      category: "Pants",
      price: 1090.99,
      description:
        "Unisex revigour 90’s skate jeans, inspired by retro skate culture. These jeans feature a relaxed fit and vintage wash, perfect for adding a nostalgic touch to your denim collection.",
      gender: "Unisex",
      image: "/skateJ.webp",
      image2: "",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 20,
    },
    {
      id: 13,
      name: "Fray Hem Denim Shorts",
      category: "Shorts",
      price: 4040.99,
      description:
        "Fray hem denim shorts, offering a laid-back and casual look. These shorts feature a frayed hem and classic denim fabric, making them a versatile choice for warm weather styling.",
      gender: "Female",
      image: "/frayHem.webp",
      image2: "/frayHem2.jpg",
      image3: "/frayHem3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 20,
    },
  
    {
      id: 14,
      name: "Distressed Hem Denim Skirt",
      category: "Skirts",
      price: 5090.99,
      description:
        "Distressed hem denim skirt, adding a touch of edge to your summer wardrobe. This denim skirt features distressed detailing and a frayed hem, perfect for creating trendy casual looks.",
      gender: "Female",
      image: "/disSkirts.webp",
      image2: "/disSkirts2.jpg",
      image3: "/disSkirts3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 20,
    },
    {
      id: 15,
      name: "Patchwork Denim Jacket",
      category: "Jackets",
      price: 9090.99,
      description:
        "Unique patchwork denim jacket for men, featuring a blend of denim patches creating an eye-catching design. This jacket is perfect for those who love to stand out from the crowd.",
      gender: "Male",
      image: "/patchWork.webp",
      image2: "/patchWork2.webp",
      image3: "/patchWork3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 20,
    },
    {
      id: 16,
      name: "Washed Pocket Denim Skirt",
      category: "Skirts",
      price: 5040.99,
      description:
        "Washed pocket denim skirt, offering a laid-back and casual look. This denim skirt features washed detailing and spacious pockets, making it a versatile choice for warm weather styling.",
      gender: "Female",
      image: "/washPocket.webp",
      image2: "/washPocket2.jpg",
      image3: "/washPocket3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 17,
      name: "Boxy Fit Denim Jacket",
      category: "Jackets",
      price: 7090.99,
      description:
        "Stylish boxy fit denim jacket, perfect for casual wear. This jacket offers a relaxed fit and timeless design, making it a staple piece for any wardrobe.",
      gender: "Male",
      image: "/boxyFit.webp",
      image2: "/boxyFit2.webp",
      image3: "/boxyFit3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 18,
      name: "Rigid Dirty Wash Carpenter Jean",
      category: "Pants",
      price: 6090.99,
      description:
        "Rigid dirty wash carpenter jeans, ideal for a rugged look. These jeans feature a durable construction and classic carpenter style, perfect for work or everyday wear.",
      gender: "Male",
      image: "/dirtyWash.webp",
      image2: "/dirtyWash2.webp",
      image3: "/dirtyWash3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 19,
      name: "Elasticated Waist Denim Shorts",
      category: "Shorts",
      price: 3090.99,
      description:
        "Elasticated waist denim shorts, providing comfort and style for your summer wardrobe. These shorts feature an elasticated waistband and denim fabric, offering a relaxed and easy-to-wear design.",
      gender: "Female",
      image: "/elasticatedShort.webp",
      image2: "/elasticatedShort2.jpg",
      image3: "/elasticatedShort3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 20,
      name: "Acid Wash Cord Jort",
      category: "Shorts",
      price: 4040.99,
      description:
        "Stylish acid wash cord jort, perfect for a vintage-inspired look. These shorts feature an acid wash finish and corduroy fabric, combining retro charm with contemporary style.",
      gender: "Male",
      image: "/cordShort.webp",
      image2: "/cordShort2.webp",
      image3: "/cordShort3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 21,
      name: "Washed Wide Leg Cargo",
      category: "Pants",
      price: 7090.99,
      description:
        "Washed wide leg cargo pants for women, combining comfort with utility-inspired style. These cargo pants feature a washed finish and spacious pockets, perfect for a laid-back yet trendy look.",
      gender: "Female",
      image: "/washedWide.webp",
      image2: "",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 22,
      name: "Rigid Frayed Multi Cargo Jeans",
      category: "Pants",
      price: 8090.99,
      description:
        "Rigid frayed multi cargo jeans, perfect for a rugged look. These jeans feature multiple cargo pockets and frayed detailing for added style and functionality.",
      gender: "Male",
      image: "/frayed.webp",
      image2: "/frayed2.webp",
      image3: "/frayed3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 23,
      name: "Split Front Denim Maxi Skirt",
      category: "Skirts",
      price: 5090.99,
      description:
        "Split front denim maxi skirt, combining elegance with casual style. This maxi skirt features a split front design and denim fabric, making it a versatile choice for both daytime and evening occasions.",
      gender: "Female",
      image: "/splitMaxi.webp",
      image2: "/splitMaxi2.jpg",
      image3: "/splitMaxi2.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 24,
      name: "Revigour Baggy Jean",
      category: "Pants",
      price: 9090.99,
      description:
        "Unisex revigour baggy jeans, offering a relaxed and urban style. These jeans feature a baggy fit and durable denim fabric, making them a versatile choice for streetwear-inspired outfits.",
      gender: "Unisex",
      image: "/reclaimedBaggy.webp",
      image2: "/reclaimedBaggy2.webp",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 25,
      name: "Baggy Rigid Overdyed Ripped Jean",
      category: "Pants",
      price: 7090.99,
      description:
        "Baggy rigid overdyed ripped jean, for a relaxed yet stylish appearance. These jeans offer a comfortable fit and distressed detailing, perfect for casual outings.",
      gender: "Male",
      image: "/overdyeRip.webp",
      image2: "/overdyeRip2.webp",
      image3: "/overdyeRip3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 26,
      name: "Volume Sleeve Denim Wrap Dress",
      category: "Dresses",
      price: 1090.99,
      description:
        "Volume sleeve denim wrap dress, featuring statement sleeves and a flattering wrap silhouette. This denim dress offers a chic and contemporary look, perfect for making a stylish statement.",
      gender: "Female",
      image: "/volDress.webp",
      image2: "/volDress2.webp",
      image3: "/volDress3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 27,
      name: "Petite Wide Leg Jean",
      category: "Pants",
      price: 6040.99,
      description:
        "Petite wide leg jeans, designed to flatter smaller frames. These jeans feature a wide leg silhouette and comfortable fit, making them a stylish choice for any occasion.",
      gender: "Female",
      image: "/petiteWide.jpg",
      image2: "/petiteWide2.jpg",
      image3: "/petiteWide3.jpg",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 15,
    },
    {
      id: 28,
      name: "Distressed Denim Shorts",
      category: "Shorts",
      price: 3090.99,
      description:
        "Distressed denim shorts, adding a rugged edge to your summer wardrobe. These shorts feature distressed detailing for a worn-in look, perfect for casual outings and weekend adventures.",
      gender: "Male",
      image: "/distShorts.webp",
      image2: "/distShorts2.webp",
      image3: "/distShorts3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
    {
      id: 29,
      name: "Collision Pitch Black Oversized Jacket",
      category: "Jackets",
      price: 1090.99,
      description:
        "Unisex collision pitch black oversized jacket, providing a sleek and modern silhouette. This jacket features an oversized fit and pitch black denim fabric, making it a versatile choice for any wardrobe.",
      gender: "Unisex",
      image: "/pitchBlack.webp",
      image2: "",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 24,
    },
    {
      id: 30,
      name: "Sea Green Wash Loose Fit Jean",
      category: "Pants",
      price: 7090.99,
      description:
        "Unisex sea green wash loose fit jeans, offering a relaxed and casual style. These jeans feature a loose fit and sea green wash, perfect for adding a pop of color to your denim collection.",
      gender: "Unisex",
      image: "/washSea.webp",
      image2: "",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 24,
    },
    {
      id: 31,
      name: "Baggy Fit Jean",
      category: "Pants",
      price: 7040.99,
      description:
        "Baggy fit jeans for a comfortable and casual look. These jeans feature a loose fit and relaxed style, making them perfect for everyday wear.",
      gender: "Male",
      image: "/baggyFit.webp",
      image2: "/baggyFit2.webp",
      image3: "/baggyFit3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 24,
    },
  
    {
      id: 32,
      name: "Revigour Loose Leg Jean",
      category: "Pants",
      price: 9040.99,
      description:
        "Unisex revigour loose leg jeans, providing a comfortable and laid-back style. These jeans feature a loose leg silhouette and classic denim fabric, perfect for everyday wear.",
      gender: "Unisex",
      image: "/reclaimedLoose.webp",
      image2: "/reclaimedLoose2.webp",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 24,
    },
    {
      id: 33,
      name: "Basic High Waisted Mom Jeans",
      category: "Pants",
      price: 6090.99,
      description:
        "Basic high waisted mom jeans, offering a timeless and flattering silhouette. These jeans feature a high waisted design and relaxed fit, perfect for creating a retro-inspired look with modern appeal.",
      gender: "Female",
      image: "/highMom.webp",
      image2: "/highMom2.webp",
      image3: "/highMom3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 24,
    },
    {
      id: 34,
      name: "Revigour Black Washed Jean",
      category: "Pants",
      price: 9090.99,
      description:
        "Unisex revigour black washed jeans, providing a sleek and modern style. These jeans feature a black washed finish and slim fit, making them a versatile choice for any wardrobe.",
      gender: "Unisex",
      image: "/blackWash.webp",
      image2: "/blackWash2.webp",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 24,
    },
    {
      id: 35,
      name: "Loose Fit Jean",
      category: "Pants",
      price: 6090.99,
      description:
        "Loose fit jeans, offering a relaxed and laid-back style, perfect for everyday wear. These jeans provide ample room for movement and are a must-have for those seeking both comfort and style.",
      gender: "Male",
      image: "/looseFit.webp",
      image2: "/looseFit2.webp",
      image3: "/looseFit3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 24,
    },
    {
      id: 36,
      name: "Denim Parachute Pant",
      category: "Pants",
      price: 8040.99,
      description:
        "Denim parachute pant, combining style with comfort. These pants feature a unique design inspired by traditional parachute pants, offering a contemporary twist to your wardrobe.",
      gender: "Male",
      image: "/parachutePants.webp",
      image2: "/parachutePants2.webp",
      image3: "/parachutePants3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 24,
    },
    {
      id: 37,
      name: "Collision Box-cut Denim Jacket",
      category: "Jackets",
      price: 9090.99,
      description:
        "Unisex collision box-cut denim jacket, offering a relaxed and edgy style. This jacket features an oversized fit and denim fabric, perfect for layering over any outfit for a bold statement.",
      gender: "Unisex",
      image: "/oversizedJ.webp",
      image2: "",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 24,
    },
    {
      id: 38,
      name: "Vintage Loose Jean",
      category: "Pants",
      price: 8090.99,
      description:
        "Unisex vintage loose jeans, offering a timeless and relaxed silhouette. These jeans feature a vintage-inspired wash and loose fit, making them a versatile choice for any casual outfit.",
      gender: "Unisex",
      image: "/vinLoose.webp",
      image2: "",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
    {
      id: 39,
      name: "Overdyed Denim Jorts",
      category: "Shorts",
      price: 4090.99,
      description:
        "Overdyed denim jorts, perfect for a casual summer look. These shorts feature an overdyed finish for a unique appearance, making them a versatile addition to your warm-weather wardrobe.",
      gender: "Male",
      image: "/overDyedShorts.webp",
      image2: "/overDyedShorts2.webp",
      image3: "/overDyedShorts3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
    {
      id: 40,
      name: "Revigour Abstract Wash Jean",
      category: "Pants",
      price: 10090.99,
      description:
        "Unisex revigour abstract wash jeans, featuring a unique and artistic design. These jeans feature an abstract wash and slim fit, perfect for making a statement with your denim.",
      gender: "Unisex",
      image: "/abstract.webp",
      image2: "",
      image3: "",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
    {
      id: 41,
      name: "Petite Distressed Denim Shorts",
      category: "Shorts",
      price: 4090.99,
      description:
        "Petite distressed denim shorts, designed to flatter smaller frames. These shorts feature distressed detailing and a classic denim fabric, making them a stylish choice for warm weather styling.",
      gender: "Female",
      image: "/petDistressed.webp",
      image2: "/petDistressed2.webp",
      image3: "/petDistressed3.webp",
      sizes: ["XS", "S", "M", "L", "XL"],
      stock: 10,
    },
  ];

return (
  <div className="products">
    {products.map((product) => (
      <ProductCard key={product.id} product={product} />
    ))}
  </div>
)